In [32]:
# importing numpy package and set this as 'np' so that in future we can call it only type 'np'
import numpy as np 
# array function calling. its just built-in function array. 
a = np.array
'''note: np.array(object, dtype=None, copy=true, order=none, subok=false, ndim=0) // array function has these default peramater ''' 
print(a)

z = np.zeros([3,2]) # zeros function return a null matrix, all the elements will be 0
z
o = np.ones([3,2]) # ones function return a unit matrix, all the elements will be 1
o

f = np.full([3,2], 5) # full function return a matrix, all the elements will be fix given by me.
f

''' R : Number of rows
C : [optional] Number of columns; By default M = N
k : [int, optional, 0 by default]
          Diagonal we require; k>0 means diagonal above main diagonal or vice versa.
dtype : [optional, float(by Default)] Data type of returned array.  '''

e = np.eye(4, 4) # eye function return a diagonal matrix, all the diagonal elements will be 1
e

''' make diagonal matrix using different value '''

df = np.diag([4,5,6])
df

<built-in function array>


array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [4]:
# make a array passing a list 
a= np.array([1,2,3,4,5,4])
print(a)
# finding type of a. 
print(type(a))

[1 2 3 4 5 4]
<class 'numpy.ndarray'>


In [6]:
# define multi dimenstional array
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [8]:
# define data type calling dtype peram 
a = np.array([[1,2,3], [4,5,6]], dtype=complex)
# data type will be complex number
print(a)
b = np.array([[1,2,3], [4,5,6]], dtype=float)
# here data type will be float number
print(b)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
# finding array size and shape 
a= np.array([1,2,3,4,5,4])
print("size of the array is : ", a.size)
print("shape of the array is : ", a.shape)

b = np.array([[1,2,3], [4,5,6]], dtype=float)
print("size of the array is : ", b.size)
print("shape of the array is : ", b.shape)
# reshape function . It can change the previous shape of the array.
c =b.reshape(3,2)
print(c)
print("shape of the array is : ", c.shape)


size of the array is :  6
shape of the array is :  (6,)
size of the array is :  6
shape of the array is :  (2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
shape of the array is :  (3, 2)


In [9]:
''' slicing in the numpy array is the way to extract a range of elements from an array. 
we can return some elements from the array as we want using slicing method. It takes row and column peram. 
here indexing will start like as list. It means row and column index will start from 0.
'''
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
''' now I will print the element which position is row 3 column 3. But in the calling array I will write 2,2. It is way to find out single element. We can also find out more element . '''
print(b[2,2])



9


In [31]:
''' "linspace" np.linspace([start], [end], [amount of numbers]) 
Return evenly spaced numbers over a specified interval.
Returns num evenly spaced samples, calculated over the interval [start, stop].
The endpoint of the interval can optionally be excluded.'''

l =np.linspace(2.0, 3.0, num=5)
l

''' numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
Return numbers spaced evenly on a log scale. '''
log = np.logspace(0,10,7, base=2)
log

array([1.00000000e+00, 3.17480210e+00, 1.00793684e+01, 3.20000000e+01,
       1.01593667e+02, 3.22539789e+02, 1.02400000e+03])