In [2]:
# importing numpy package and set this as 'np' so that in future we can call it only type 'np'
import numpy as np 
# array function calling. its just built-in function array. 
a = np.array
'''note: np.array(object, dtype=None, copy=true, order=none, subok=false, ndim=0) // array function has these default peramater ''' 
print(a)


<built-in function array>


In [4]:
# make a array passing a list 
a= np.array([1,2,3,4,5,4])
print(a)
# finding type of a. 
print(type(a))

[1 2 3 4 5 4]
<class 'numpy.ndarray'>


In [6]:
# define multi dimenstional array
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [8]:
# define data type calling dtype peram 
a = np.array([[1,2,3], [4,5,6]], dtype=complex)
# data type will be complex number
print(a)
b = np.array([[1,2,3], [4,5,6]], dtype=float)
# here data type will be float number
print(b)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
# finding array size and shape 
a= np.array([1,2,3,4,5,4])
print("size of the array is : ", a.size)
print("shape of the array is : ", a.shape)

b = np.array([[1,2,3], [4,5,6]], dtype=float)
print("size of the array is : ", b.size)
print("shape of the array is : ", b.shape)

size of the array is :  6
shape of the array is :  (6,)
size of the array is :  6
shape of the array is :  (2, 3)
