In [2]:
# importing numpy package and set this as 'np' so that in future we can call it only type 'np'
import numpy as np 
# array function calling. its just built-in function array. 
a = np.array
'''note: np.array(object, dtype=None, copy=true, order=none, subok=false, ndim=0) // array function has these default peramater ''' 
print(a)

z = np.zeros([3,2]) # zeros function return a null matrix, all the elements will be 0
z
o = np.ones([3,2]) # ones function return a unit matrix, all the elements will be 1
o

f = np.full([3,2], 5) # full function return a matrix, all the elements will be fix given by me.
f

''' R : Number of rows
C : [optional] Number of columns; By default M = N
k : [int, optional, 0 by default]
          Diagonal we require; k>0 means diagonal above main diagonal or vice versa.
dtype : [optional, float(by Default)] Data type of returned array.  '''

e = np.eye(4, 4) # eye function return a diagonal matrix, all the diagonal elements will be 1
e

''' make diagonal matrix using different value '''

df = np.diag([4,5,6])
df

<built-in function array>


array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [4]:
# make a array passing a list 
a= np.array([1,2,3,4,5,4])
print(a)
# finding type of a. 
print(type(a))

[1 2 3 4 5 4]
<class 'numpy.ndarray'>


In [6]:
# define multi dimenstional array
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [8]:
# define data type calling dtype peram 
a = np.array([[1,2,3], [4,5,6]], dtype=complex)
# data type will be complex number
print(a)
b = np.array([[1,2,3], [4,5,6]], dtype=float)
# here data type will be float number
print(b)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
# finding array size and shape 
a= np.array([1,2,3,4,5,4])
print("size of the array is : ", a.size)
print("shape of the array is : ", a.shape)

b = np.array([[1,2,3], [4,5,6]], dtype=float)
print("size of the array is : ", b.size)
print("shape of the array is : ", b.shape)
# reshape function . It can change the previous shape of the array.
c =b.reshape(3,2)
print(c)
print("shape of the array is : ", c.shape)


size of the array is :  6
shape of the array is :  (6,)
size of the array is :  6
shape of the array is :  (2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
shape of the array is :  (3, 2)


In [9]:
''' slicing in the numpy array is the way to extract a range of elements from an array. 
we can return some elements from the array as we want using slicing method. It takes row and column peram. 
here indexing will start like as list. It means row and column index will start from 0.
'''
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
''' now I will print the element which position is row 3 column 3. But in the calling array I will write 2,2. It is way to find out single element. We can also find out more element . '''
print(b[2,2])



9


In [31]:
''' "linspace" np.linspace([start], [end], [amount of numbers]) 
Return evenly spaced numbers over a specified interval.
Returns num evenly spaced samples, calculated over the interval [start, stop].
The endpoint of the interval can optionally be excluded.'''

l =np.linspace(2.0, 3.0, num=5)
l

''' numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
Return numbers spaced evenly on a log scale. '''
log = np.logspace(0,10,7, base=2)
log

array([1.00000000e+00, 3.17480210e+00, 1.00793684e+01, 3.20000000e+01,
       1.01593667e+02, 3.22539789e+02, 1.02400000e+03])

In [34]:
# maximum, minimum, sum
b = np.array([[1,2,3], [4,5,6]])
print("max number from this array is: ", b.max())
print("min number from this array is: ", b.min())
print("sum of this array is: ", b.sum())


max number from this array is:  6
min number from this array is:  1
sum of this array is:  21


In [35]:
# squar root, standard deviation
b = np.array([[1,2,3], [4,5,6]])
print("square root of every element from this array are: ", np.sqrt(b))
print("standard deviation of this array is: ", np.std(b))

square root of every element from this array are:  [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
standard deviation of this array is:  1.707825127659933


In [38]:
# addition, subtraction, multiplication, devision 
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,8,3], [5,5,4]])
 
print("addition of two array is : \n", x + y)
print("subtraction of two array is: \n", x - y)
print("multiplication of two array is: \n", x * y)
print("devision of two array is: \n", x / y)


addition of two array is : 
 [[ 5 10  6]
 [ 9 10 10]]
subtraction of two array is: 
 [[-3 -6  0]
 [-1  0  2]]
multiplication of two array is: 
 [[ 4 16  9]
 [20 25 24]]
devision of two array is: 
 [[0.25 0.25 1.  ]
 [0.8  1.   1.5 ]]


In [40]:
# vertically and horizontally concatenation  
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,8,3], [5,5,4]])
print("verticall concatenation between x and y is : \n", np.vstack((x,y)))
print("horizontal concatenation between x and y is : \n", np.hstack((x,y)))


verticall concatenation between x and y is : 
 [[1 2 3]
 [4 5 6]
 [4 8 3]
 [5 5 4]]
horizontal concatenation between x and y is : 
 [[1 2 3 4 8 3]
 [4 5 6 5 5 4]]


In [61]:
# numpy empty array
empty = np.empty((3,2), dtype='int')
empty

array([[1756492160,        342],
       [         0,          0],
       [    131074, 1714319470]])

In [68]:
# numpy asarray 
list = [1,2,5,4,8,3,4]
a = np.asarray(list)
print(a)
tuple = (1,2,5,4,8,3,4)
b = np.asarray(tuple)
print(b)

[1 2 5 4 8 3 4]
[1 2 5 4 8 3 4]


In [4]:
# numpy array iteration 
x = np.array([[1,2,3], [4,5,6]])
for i in np.nditer(x):
    print(i)
# numpy array transpose
tr = x.T
print(tr)

1
2
3
4
5
6
[[1 4]
 [2 5]
 [3 6]]


In [6]:
# numpy bitwise operator
a = 10
b = 12
print(bin(a))
print(bin(b))
# bitwise AND
print("Bitwise AND of a and b : ", np.bitwise_and(a,b))
print(bin(np.bitwise_and(a,b)))
# bitwise OR
print("Bitwise OR of a and b : ", np.bitwise_or(a,b))
print(bin(np.bitwise_or(a,b)))

0b1010
0b1100
Bitwise AND of a and b :  8
0b1000
Bitwise OR of a and b :  14
0b1110


In [22]:
# numpy string function
# add funtcion can use for string concatenation 
a = np.char.add(['hi'], ['shuvro'])
print(a)

# multiplication 
print(np.char.multiply('hello', 3))

# center
print(np.char.center('hello', 20, '_'))

# title
print(np.char.title('hello shuvro baset' ))
# lower, upper .... 

# split
print(np.char.split('hello shuvro baset' ),sep=" ")

# strip
print(np.char.strip('   hello shuvro baset' ))

# join
print(np.char.join( ":", 'hello shuvro baset' ))

# replace
sample_string = 'hi'
print(np.char.replace(sample_string, "hi", "hello"))

# encode decode
en_str = np.char.encode("welcome to numpy", "cp500")
dc_str = np.char.decode(en_str, 'cp500')
print(en_str)
print(dc_str)

['hishuvro']
hellohellohello
_______hello________
Hello Shuvro Baset
['hello', 'shuvro', 'baset']
hello shuvro baset
h:e:l:l:o: :s:h:u:v:r:o: :b:a:s:e:t
hello
b'\xa6\x85\x93\x83\x96\x94\x85@\xa3\x96@\x95\xa4\x94\x97\xa8'
welcome to numpy


In [25]:
# numpy mathemetical functions
# trigonometry
array = np.array([0,30,45,60,90])
print("Sin value of an agle is: ")
print(np.sin(array*np.pi/180))

# rounding function 
array = np.array([35,45,64,95])
print("array values rounded off 2 decimal position: ", np.around(array, 2))
print("array values rounded -1 decimal position: ", np.around(array,-1))

# floor function can ignore the decimal point after the Integer number
# ceil function can rounded the number, like if a number is 4.5 it will return 5 



Sin value of an agle is: 
[0.         0.5        0.70710678 0.8660254  1.        ]
array values rounded off 2 decimal position:  [35 45 64 95]
array values rounded -1 decimal position:  [ 40  40  60 100]


In [32]:
# numPy statistical functions 

a = np.array([[54,10,45], [4,55,44,], [47,65,60]])
print(a)
print("the minimum element among the array: ", np.amin(a))
print("the minimum element among the array: ", np.amax(a))

print("the minimum element among the column of the array: ", np.amin(a,0))
print("the minimum element among the column of  the array: ", np.amax(a, 0))

print("the minimum element among the row of  the array: ", np.amin(a,1))
print("the minimum element among the row of  the array: ", np.amax(a,1))

# ptp (peak to peak)
print("PTP value along with axis 1 means row wise: ", np.ptp(a,1))
print("PTP value along with axis 0 means column wise: ", np.ptp(a,0))

print(a)
# percentile
print("percentile along with axis 0: ", np.percentile(a,10,0))
print("percentile along with axis 1: ", np.percentile(a,10,1))

[[54 10 45]
 [ 4 55 44]
 [47 65 60]]
the minimum element among the array:  4
the minimum element among the array:  65
the minimum element among the column of the array:  [ 4 10 44]
the minimum element among the column of  the array:  [54 65 60]
the minimum element among the row of  the array:  [10  4 47]
the minimum element among the row of  the array:  [54 55 65]
PTP value along with axis 1 means row wise:  [44 51 18]
PTP value along with axis 0 means column wise:  [50 55 16]
[[54 10 45]
 [ 4 55 44]
 [47 65 60]]
percentile along with axis 0:  [12.6 19.  44.2]
percentile along with axis 1:  [17.  12.  49.6]


In [35]:
# median mean average
a = np.array([[54,10,45], [4,55,44,], [47,65,60]])
print(a)

print("the minimum element among the column of the array: ", np.mean(a))
print("the minimum element among the column of  the array: ", np.median(a))
print("the minimum element among the column of  the array: ", np.average(a))


[[54 10 45]
 [ 4 55 44]
 [47 65 60]]
the minimum element among the column of the array:  42.666666666666664
the minimum element among the column of  the array:  47.0
the minimum element among the column of  the array:  42.666666666666664


In [36]:
# numpy sorting
a = np.array([[54,10,45], [4,55,44,], [47,65,60]])
print("array is printed in sorted form: ", np.sort(a))
print("Sorting along the rows: ", np.sort(a, 0))

array is printed in sorted form:  [[10 45 54]
 [ 4 44 55]
 [47 60 65]]
Sorting along the rows:  [[ 4 10 44]
 [47 55 45]
 [54 65 60]]


In [38]:
# numpy searching 
a = np.array([[54,10,45], [4,55,44,], [47,65,60]])
print(np.where(a>20))
b = np.array([5,4,40,45,80,41,10])
print(np.where(b>20))

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64), array([0, 2, 1, 2, 0, 1, 2], dtype=int64))
(array([2, 3, 4, 5], dtype=int64),)


In [46]:
# numpy with linear algebra
x = np.array([[100,200], [23,12]])
y = np.array([[10,20], [12,21]])
# dot function is like as array multiplication linear way
dot = np.dot(x,y)
print(dot)
# vdot function multiplied with row by row 
print(np.vdot(x,y))
# matmul same as dot
print(np.matmul(x,y))
# determinant
print(np.linalg.det(x))
print(np.linalg.det(y))

# matrix inverse
print(np.linalg.inv(x))
print(np.linalg.inv(y))

[[3400 6200]
 [ 374  712]]
5528
[[3400 6200]
 [ 374  712]]
-3399.999999999999
-30.000000000000004
[[-0.00352941  0.05882353]
 [ 0.00676471 -0.02941176]]
[[-0.7         0.66666667]
 [ 0.4        -0.33333333]]


In [ ]:
'''numpy save function can save a file as a new file
a = np.array([....])
np.save('file name' a)

'''